# ~/.config/alacritty/alacritty.toml

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Full"
opacity = 0.9

[font]
size = 12.0

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = "Beam"


[colors.primary]
background = "#000000"
foreground = "0xd9e0ee"

[colors.normal]
black   = "0x1e1e2e"
red     = "0xf38ba8"
green   = "0xa6e3a1"
yellow  = "0xf9e2af"
blue    = "0x89b4fa"
magenta = "0xf5c2e7"
cyan    = "0x94e2d5"
white   = "0xd9e0ee"

[colors.bright]
black   = "0x585b70"
red     = "0xf38ba8"
green   = "0xa6e3a1"
yellow  = "0xf9e2af"
blue    = "0x89b4fa"
magenta = "0xf5c2e7"
cyan    = "0x94e2d5"
white   = "0xffffff"

[keyboard]
bindings = [
  {key = "V", mods = "Control|Shift", action = "Paste"},
  {key = "C", mods = "Control|Shift", action = "Copy"},
]
